spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///vuedate?characterEncoding=utf8&useSSL=false&useLocalSessionState=true
    username: root
    password: 123456
  redis:
    host: http://localhost
    port: 6379
    password: admin
    timeout: 5000
    database: 0
    jedis:
      pool:
        max-idle: 8
        max-wait:
        min-idle: 0
  rabbitmq:
    username: zzn
    password: admin
    port: 5672
    host: localhost
    listener:
      simple:
        #消费手动确认
        acknowledge-mode: manual
  klock:
    address: 127.0.0.1:6379
    password: admin



mybatis:
  mapperLocations: classpath:mapper/*.xml
server:
  port: 80